name: Markdownlint
on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: articulate/actions-markdownlint@v1
        with:
          config: markdownlint-config.json
          files: 'docs/**/*.md'
          ignore: node_modules
          version: 0.28.1
